### PR TITLE
originate in user and device mode

### PR DESCRIPTION
**Pull request by wizhippo**
Originate using the correct extension for originate when in user and device mode.

### CODE REVIEW

**Comment by tm1000** [comment]
You get $data but then you never use $data again

**Comment by wizhippo** [comment]
Data is just used to make sure an device exists before we try to originate to the user.  We could blindly send it the 'from'.  To be honest I'm not sure why the check for the device in the first place.

**Comment by tm1000** [comment]
It's used to prevent callerid spoofing. However it could probably be checked by just checking what the default extension is of the user from usermanager

**Comment by wizhippo** [comment]
@tm1000 thanks for the clarification and direction.  Is this better?

**Comment by tm1000** [comment]
Yes that is perfect! thanks!

**Pull request merged**
